"""
Given two logic nodes, A and B are connected by a directed edge, from A to B. 
A generate data at the rate of freq_A, and B process data at the rate of freq_B;  
if freq_A>freq_B, B only accept the requests, which satisfy i == int(j/freq_B*freq_A); 
if freq_A < freq_B, the ith data generated by A is reused by the jth process of B, and j == i+freq_A*t, 
and each data generated by A is reused for at most math.ceil(freq_B/freq_A) times
Here i and j are the index of requests of A and B, respectively. 
Now we are going to scale the processing parallelism of two nodes, 
with the factor S_A, and S_B, i.e., A is duplicated S_A times (A_i, i = 0, ..., S_{A-1}), 
and B is reproduced S_B times  (B_i, i = 0, ..., S_{B-1}). 
Simultaneously, the processing load is partitioned, 
A_i process math.ceil(freq_A/s_A) data requests and B_i gets math.ceil(freq_B/s_B).
Write me a Python code to rebuild the data relationship of the duplicated nodes, 
and represent the graph with networkx packet.

Example 1:
freq_A = 3
freq_B = 1
S_A = 3
S_B = 1

idx_data_A = [0, 1, 2,]
idx_A = [0, 1, 2,]
idx_B = [0, x, x,]
idx_data_B = [0, x, x,]

"""
import math
import networkx as nx
import matplotlib.pyplot as plt

def build_data_node_relationship(G:nx.DiGraph, freq_A:int, freq_B:int, S_A:int, S_B:int, A_n:str, B_n:str, dispatch_mode:str='interleave'):
    for i in range(S_A):
        A_node = f"{A_n}_{i}"
        G.add_node(A_node)
        for j in range(S_B):
            B_node = f"{B_n}_{j}"
            G.add_node(B_node)
            for k in range(math.ceil(freq_A / S_A)):
                A_data = f"{A_n}_{i}_{k}"
                G.add_node(A_data)
                G.add_edge(A_data, A_node)
                A_data_idx = i * math.ceil(freq_A / S_A) + k
                for l in range(math.ceil(freq_B / S_B)):
                    B_data = f"{B_n}_{j}_{l}"
                    G.add_node(B_data)
                    G.add_edge(B_node, B_data)
                    B_data_idx = j * math.ceil(freq_B / S_B) + l
                    if freq_A >= freq_B:
                        # i == int(j/freq_B*freq_A)
                        if A_data_idx == int(B_data_idx / freq_B * freq_A):
                            G.add_edge(A_node, B_node)
                    else:
                        # j == i+freq_A*t
                        assert dispatch_mode in ['interleave', 'repeat']
                        if dispatch_mode == 'interleave':
                            if A_data_idx == B_data_idx % freq_A:
                                G.add_edge(A_node, B_node)
                        elif dispatch_mode == 'repeat':
                            if A_data_idx == int(B_data_idx / freq_B * freq_A):
                                G.add_edge(A_node, B_node)
    return G

def build_node_relationship(G:nx.DiGraph, freq_A:int, freq_B:int, S_A:int, S_B:int, A_n:str, B_n:str, dispatch_mode:str='interleave'):
    for i in range(S_A):
        A_node = f"{A_n}_{i}"
        G.add_node(A_node)
        for j in range(S_B):
            B_node = f"{B_n}_{j}"
            G.add_node(B_node)
            for k in range(math.ceil(freq_A / S_A)):
                # A_data = f"{A_n}_{i}_{k}"
                # G.add_node(A_data)
                # G.add_edge(A_data, A_node)
                A_data_idx = i * math.ceil(freq_A / S_A) + k
                for l in range(math.ceil(freq_B / S_B)):
                    # B_data = f"{B_n}_{j}_{l}"
                    # G.add_node(B_data)
                    # G.add_edge(B_node, B_data)
                    B_data_idx = j * math.ceil(freq_B / S_B) + l
                    if freq_A > freq_B:
                        # i == int(j/freq_B*freq_A)
                        if A_data_idx == int(B_data_idx / freq_B * freq_A):
                            G.add_edge(A_node, B_node)
                    else:
                        # j == i+freq_A*t
                        assert dispatch_mode in ['interleave', 'repeat']
                        if dispatch_mode == 'interleave':
                            if A_data_idx == B_data_idx % freq_A:
                                G.add_edge(A_node, B_node)
                        elif dispatch_mode == 'repeat':
                            if A_data_idx == int(B_data_idx / freq_B * freq_A):
                                G.add_edge(A_node, B_node)
    return G


if __name__ == "__main__":
    # Example usage
    G = nx.DiGraph()
    A_n = "A_node"
    B_n = "B_node"

    # freq_A = 3
    # freq_B = 1
    # S_A = 3
    # S_B = 1

    # freq_A = 3
    # freq_B = 24
    # S_A = 3
    # S_B = 1

    freq_A = 3
    freq_B = 1
    S_A = 3
    S_B = 1

    G = build_data_node_relationship(G, freq_A, freq_B, S_A, S_B, A_n, B_n)

    # Print the nodes and edges of the graph
    print("Nodes:", G.nodes())
    print("Edges:", G.edges())

    # Visualize the graph
    # nx.draw(G, with_labels=True)

    for layer, nodes in enumerate(nx.topological_generations(G)):
        # `multipartite_layout` expects the layer as a node attribute, so add the
        # numeric layer value as a node attribute
        for node in nodes:
            G.nodes[node]["layer"] = layer
    pos = nx.multipartite_layout(G, subset_key="layer")
    nx.draw(G, pos, with_labels=False, node_size=100, font_size=10, )
    text = nx.draw_networkx_labels(G, pos, font_size=10, )
    for _, t in text.items():
        t.set_rotation(30)
    plt.savefig("plot/scaling.pdf", format="pdf")
