trace_example = {
    'trigger': {
        'IMU_pub': {
            'trigger': {
                'trigger_time': 0.0},
            'src': {},
            'weight': {},
            'process_info': {},
            'data_type': 'sensor',
            'data_info': {},
            'transfer_info': {}}},
    'src': {
        'Planning_0': {
            'trigger': {},
            'src': {
                'Prediction_0': {
                    'trigger': {},
                    'src': {
                        'Lidar_based_3dDet_0': {
                            'trigger': {
                                'LiDAR_pub': {
                                    'trigger': {
                                        'trigger_time': 0.0},
                                    'src': {},
                                    'weight': {},
                                    'process_info': {},
                                    'data_type': 'sensor',
                                    'data_info': {},
                                    'transfer_info': {}}},
                            'src': {
                                'Semantic_segm_0': {
                                    'trigger': {},
                                    'src': {
                                        'Stereo_feature_enc_0': {
                                            'trigger': {
                                                'streo_camera_pub': {
                                                    'trigger': {
                                                        'trigger_time': 0.0},
                                                    'src': {},
                                                    'weight': {},
                                                    'process_info': {},
                                                    'data_type': 'sensor',
                                                    'data_info': {},
                                                    'transfer_info': {}}},
                                            'src': {},
                                                'weight': {},
                                                'process_info': {
                                                    'pid': 19,
                                                    'name': 'Stereo_feature_enc_0',
                                                    'start_time': 0.0,
                                                    'downstream_node': ['Semantic_segm_0',
                                                                        'Lane_drivable_area_det_0',
                                                                        'Optical_Flow_0',
                                                                        'Depth_estimation_0'],
                                                    'ready_time': 0.0,
                                                    'end_time': 0.0066600014519999995,
                                                    'processing_time': 0.006163703266874946},
                                                'data_type': 'process',
                                                'data_info': {
                                                    'pid': 19,
                                                    'size': 1,
                                                    'data_id': (0,),
                                                    'data_type': 'output',
                                                    'waitTime': 0,
                                                    'io_time': 1e-06,
                                                    'event_time': 0.0066600014519999995,
                                                    'life_time': 0.05},
                                                'transfer_info': {
                                                    'start_time': 0.0066600014519999995,
                                                    'end_time': 0.0066600014519999995}}},
                                    'weight': {},
                                        'process_info': {
                                            'pid': 21,
                                            'name': 'Semantic_segm_0',
                                            'start_time': 0.0066600014519999995,
                                            'downstream_node': ['Lidar_based_3dDet_0'],
                                            'ready_time': 0.0066600014519999995,
                                            'end_time': 0.012636925831999999,
                                            'processing_time': 0.005427260798624953},
                                        'data_type': 'process',
                                        'data_info': {
                                            'pid': 21,
                                            'size': 1,
                                            'data_id': (0,),
                                            'data_type': 'output',
                                            'waitTime': 0,
                                            'io_time': 1e-06,
                                            'event_time': 0.012636925831999999,
                                            'life_time': 0.05},
                                        'transfer_info': {
                                            'start_time': 0.012636925831999999,
                                            'end_time': 0.012636925831999999}}},
                                'weight': {},
                                'process_info': {
                                    'pid': 23,
                                    'name': 'Lidar_based_3dDet_0',
                                    'start_time': 0.012636925831999999,
                                    'downstream_node': ['Prediction_0',
                                                        'Prediction_1',
                                                        'Prediction_2'],
                                    'ready_time': 0.012636925831999999,
                                    'end_time': 0.015886878463625,
                                    'processing_time': 0.001777067695124988},
                                'data_type': 'process',
                                'data_info': {
                                    'pid': 23,
                                    'size': 1,
                                    'data_id': (0,),
                                    'data_type': 'output',
                                    'waitTime': 0,
                                    'io_time': 1e-06,
                                    'event_time': 0.015886878463625,
                                    'life_time': 0.1},
                                'transfer_info': {
                                    'start_time': 0.015886878463625,
                                    'end_time': 0.015886878463625}},
                        'Pure_camera_path_head_0': {
                                'trigger': {},
                                'src': {
                                    'MultiCameraFusion_0': {
                                        'trigger': {},
                                        'src': {
                                            'ImageBB_0': {
                                                'trigger': {
                                                    'surr_view_camera_pub': {
                                                        'trigger': {
                                                            'trigger_time': 0.0},
                                                        'src': {},
                                                        'weight': {},
                                                        'process_info': {},
                                                        'data_type': 'sensor',
                                                        'data_info': {},
                                                        'transfer_info': {}}},
                                                'src': {},
                                                'weight': {},
                                                'process_info': {
                                                    'pid': 3,
                                                    'name': 'ImageBB_0',
                                                    'start_time': 0.0,
                                                    'downstream_node': ['MultiCameraFusion_0'],
                                                    'ready_time': 0.0,
                                                    'end_time': 0.028833323593875,
                                                    'processing_time': 0.02471351500337456},
                                                'data_type': 'process',
                                                'data_info': {
                                                    'pid': 3,
                                                    'size': 1,
                                                    'data_id': (0,),
                                                    'data_type': 'output',
                                                    'waitTime': 0,
                                                    'io_time': 1e-06,
                                                    'event_time': 0.028833323593875,
                                                    'life_time': 0.03333333333333333},
                                                'transfer_info': {
                                                    'start_time': 0.028833323593875,
                                                    'end_time': 0.028833323593875}}},
                                        'weight': {},
                                        'process_info': {
                                            'pid': 6,
                                            'name': 'MultiCameraFusion_0',
                                            'start_time': 0.028833323593875,
                                            'downstream_node': ['Pure_camera_path_head_0'],
                                            'ready_time': 0.028833323593875,
                                            'end_time': 0.032040583908499995,
                                            'processing_time': 0.0025775486388749805},
                                        'data_type': 'process',
                                        'data_info': {
                                            'pid': 6,
                                            'size': 1,
                                            'data_id': (0,),
                                            'data_type': 'output',
                                            'waitTime': 0,
                                            'io_time': 1e-06,
                                            'event_time': 0.032040583908499995,
                                            'life_time': 0.03333333333333333},
                                        'transfer_info': {
                                            'start_time': 0.032040583908499995,
                                            'end_time': 0.032040583908499995}}},
                                'weight': {},
                                'process_info': {
                                    'pid': 9,
                                    'name': 'Pure_camera_path_head_0',
                                    'start_time': 0.032040583908499995,
                                    'downstream_node': ['Prediction_0'],
                                    'ready_time': 0.032040583908499995,
                                    'end_time': 0.04007741258375,
                                    'processing_time': 0.007012213067249938},
                                'data_type': 'process',
                                'data_info': {
                                    'pid': 9,
                                    'size': 1,
                                    'data_id': (0,),
                                    'data_type': 'output',
                                    'waitTime': 0,
                                    'io_time': 1e-06,
                                    'event_time': 0.04007741258375,
                                    'life_time': 0.03333333333333333},
                                'transfer_info': {
                                    'start_time': 0.04007741258375,
                                    'end_time': 0.04007741258375}}},
                    'weight': {},
                        'process_info': {
                            'pid': 12,
                            'name': 'Prediction_0',
                            'start_time': 0.04007741258375,
                            'downstream_node': ['Planning_0'],
                            'ready_time': 0.04007741258375,
                            'end_time': 0.04261760544525,
                            'processing_time': 0.0015422599516249902},
                        'data_type': 'process',
                        'data_info': {
                            'pid': 12,
                            'size': 1,
                            'data_id': (0,),
                            'data_type': 'output',
                            'waitTime': 0,
                            'io_time': 1e-06,
                            'event_time': 0.04261760544525,
                            'life_time': 0.03333333333333333},
                        'transfer_info': {
                            'start_time': 0.04261760544525,
                            'end_time': 0.04261760544525}}},
            'weight': {},
            'process_info': {
                'pid': 15,
                    'name': 'Planning_0',
                    'start_time': 0.04261760544525,
                    'downstream_node': ['Steering_speed_0'],
                    'ready_time': 0.04261760544525,
                    'end_time': 0.044949673261375,
                    'processing_time': 0.0017130292196249886},
            'data_type': 'process',
                'data_info': {
                    'pid': 15,
                    'size': 1,
                    'data_id': (0,),
                    'data_type': 'output',
                    'waitTime': 0,
                    'io_time': 1e-06,
                    'event_time': 0.044949673261375,
                    'life_time': 0.03333333333333333},
            'transfer_info': {
                    'start_time': 0.044949673261375,
                    'end_time': 0.044949673261375}}},
    'weight': {},
        'process_info': {
        'pid': 18,
        'name': 'Steering_speed_0',
        'start_time': 0.044949673261375,
        'downstream_node': [],
        'ready_time': 0.044949673261375,
        'end_time': 0.045536692620125,
        'processing_time': 0.0002401442831250001},
    'data_type': 'process',
    'data_info': {
        'pid': 18,
        'size': 1,
        'data_id': (0,),
        'data_type': 'output',
        'waitTime': 0,
        'io_time': 1e-06,
        'event_time': 0.045536692620125,
        'life_time': 0.004166666666666667},
    'transfer_info': {
            'start_time': 0.045536692620125}}

